#!/bin/bash
# agent-zero-persistent Management Script
# Generated by docker-persistent-deploy skill

CONTAINER_NAME="agent-zero-persistent"
IMAGE="agent0ai/agent-zero"
DATA_DIR="$(cd "$(dirname "$0")" && pwd)/docker/run/agent-zero"
HOST_PORT=50080
CONTAINER_PORT=80
CONTAINER_DATA_PATH="/a0"
EXTRA_PORTS="-p 8822:22"

case "$1" in
    start)
        echo "Starting ${CONTAINER_NAME}..."
        docker run -d \
            --name "${CONTAINER_NAME}" \
            -p ${HOST_PORT}:${CONTAINER_PORT} \
            ${EXTRA_PORTS} \
            -v "${DATA_DIR}:${CONTAINER_DATA_PATH}" \
            --restart unless-stopped \
            "${IMAGE}"
        echo "Container started on port ${HOST_PORT}"
        echo "Web UI: http://127.0.0.1:${HOST_PORT}"
        ;;
    stop)
        echo "Stopping ${CONTAINER_NAME}..."
        docker stop "${CONTAINER_NAME}"
        docker rm "${CONTAINER_NAME}"
        echo "Container stopped and removed"
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start
        ;;
    status)
        docker ps -a --filter "name=${CONTAINER_NAME}" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
        ;;
    logs)
        docker logs -f "${CONTAINER_NAME}"
        ;;
    backup)
        "$(dirname "$0")/backup-agent-zero-persistent.sh"
        ;;
    update)
        echo "Creating backup before update..."
        $0 backup
        echo "Pulling latest image..."
        docker pull "${IMAGE}"
        echo "Restarting with new image..."
        $0 restart
        ;;
    shell)
        docker exec -it "${CONTAINER_NAME}" /bin/bash
        ;;
    *)
        echo "Agent Zero Persistent Docker Management"
        echo ""
        echo "Usage: $0 {start|stop|restart|status|logs|backup|update|shell}"
        echo ""
        echo "Commands:"
        echo "  start   - Start the container"
        echo "  stop    - Stop and remove the container"
        echo "  restart - Stop and start the container"
        echo "  status  - Show container status"
        echo "  logs    - Follow container logs"
        echo "  backup  - Create a backup of data"
        echo "  update  - Pull latest image and restart"
        echo "  shell   - Open bash shell in container"
        echo ""
        echo "Data directory: ${DATA_DIR}"
        echo "Web UI: http://127.0.0.1:${HOST_PORT}"
        exit 1
        ;;
esac
