#!/bin/bash
# Backup script for agent-zero-persistent
# Generated by docker-persistent-deploy skill

DATA_DIR="$(cd "$(dirname "$0")" && pwd)/docker/run/agent-zero"
BACKUP_DIR="${DATA_DIR}/backups"
RETENTION_DAYS=7
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p "${BACKUP_DIR}"

echo "=== Agent Zero Backup ==="
echo "Data directory: ${DATA_DIR}"
echo "Backup directory: ${BACKUP_DIR}"
echo "Timestamp: ${TIMESTAMP}"
echo ""

echo "Creating backup: backup_${TIMESTAMP}.tar.gz"
tar -czf "${BACKUP_DIR}/backup_${TIMESTAMP}.tar.gz" \
    -C "${DATA_DIR}" \
    --exclude="backups" \
    --exclude="*.log" \
    .

if [ $? -eq 0 ]; then
    BACKUP_SIZE=$(du -h "${BACKUP_DIR}/backup_${TIMESTAMP}.tar.gz" | cut -f1)
    echo "Backup created successfully (${BACKUP_SIZE})"
else
    echo "ERROR: Backup failed!"
    exit 1
fi

# Cleanup old backups
echo ""
echo "Cleaning up backups older than ${RETENTION_DAYS} days..."
DELETED=$(find "${BACKUP_DIR}" -name "backup_*.tar.gz" -mtime +${RETENTION_DAYS} -delete -print | wc -l)
echo "Deleted ${DELETED} old backup(s)"

echo ""
echo "Current backups:"
ls -lah "${BACKUP_DIR}"/backup_*.tar.gz 2>/dev/null || echo "No backups found"

echo ""
echo "=== Backup Complete ==="
